#
# 嘿！哥们，这里没有你想要的配置文件，只有数据库的连接信息
#
# 首先你得部署好 MongoDB 否则就算配置文件生成出来插件也不能正常运行
# 然后修改下方的连接配置，之后运行一次
# 主要的配置文件会被生成到 MongoDB 中(与其他插件不同哦！)
# 按需修改即可
#
# 另外，所有子插件的配置文件也全部在 MongoDB 中
# 如果 MongoDB 坏了...祝你好运哈哈哈
#

# 数据库连接信息
mongo_connection_url: "mongodb://localhost:27017/"
# 数据库名称 如果数据库不存在会自动创建
mongo_database_name: "wolfird_db"