name: WolfirdFramework
version: '${version}'
main: org.wolflink.minecraft.wolfird.framework.Framework
api-version: 1.12
load: STARTUP
authors: [WolfLink-DevTeam]
commands:
  wolfird:
    aliases:
      - wf